[manifest]
version = "1.0.0"
dump_lua = true
priority = 1




# Add Temporary badge
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''local badges = {}'''
position = "after"
payload = '''
if self.ability.cs_temp.active then
    badges[#badges + 1] = 'cs_temporary'
end
'''
match_indent = true




# Add Temporary info queue
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''for k, v in ipairs(badges) do'''
position = "after"
payload = '''
    if v == 'cs_temporary' then info_queue[#info_queue + 1] = {key = 'cs_temporary', set = 'Other'} end
'''
match_indent = true




# Add primary set for Alignment
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
        SET = {
'''
position = "after"
payload = '''
            Alignment = HEX('c45023'),
'''
match_indent = true




# Add secondary set for Alignment
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''
        SECONDARY_SET = {
'''
position = "after"
payload = '''
            Alignment = HEX('f5af6f'),
'''
match_indent = true