[manifest]
version = "1.0.0"
dump_lua = true
priority = 1




# Add off-screen Stack area
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''G.SPLASH_BACK = Sprite(-30, -6, G.ROOM.T.w+60, G.ROOM.T.h+12, G.ASSET_ATLAS["ui_1"], {x = 2, y = 0})'''
position = "before"
payload = '''

self.cs_stack_W = 4.9*G.CARD_W
self.cs_stack_H = 0.95*G.CARD_H

self.cs_stack = CardArea(
    G.jokers.T.x,
    G.jokers.T.y - (G.jokers.T.h*2), 
    self.cs_stack_W, 
    self.cs_stack_H, 
    {card_limit = 5, type = 'cs_stack', highlight_limit = 0}
)
'''
match_indent = true




# Add 2 more Hand cardareas for Call the Orb
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''self.hand = CardArea('''
position = "before"
payload = '''
self.hand_3 = CardArea(
    (G.TILE_W - CAI.hand_W)- 2.85,
    (G.TILE_H - CAI.hand_H) - 6,
    CAI.hand_W,
    CAI.hand_H, 
    {card_limit = self.GAME.starting_params.hand_size, type = 'hand'})

self.hand_2 = CardArea(
    (G.TILE_W - CAI.hand_W) - 2.85,
    (G.TILE_H - CAI.hand_H) - 4,
    CAI.hand_W,
    CAI.hand_H, 
    {card_limit = self.GAME.starting_params.hand_size, type = 'hand'})
'''
match_indent = true




# Remove card count from extra hands (since they share the  same  limit of original hand)
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''
                    {n=G.UIT.B, config={w = 0.1,h=0.1}}
                }} or nil
'''
position = "after"
payload = '''
if self == G.hand_2 or self == G.hand_3 then card_count = nil end
'''
match_indent = true