[manifest]
version = "1.0.0"
dump_lua = true
priority = 1




# Context for when you Cash out
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
                end
            }))
          G.STATE_COMPLETE = true
'''
position = "after"
payload = '''
SMODS.calculate_context({cs_entering_shop = true})
'''
match_indent = true




# Context for when you play the cards, before it does anything else
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.hands[text].played = G.GAME.hands[text].played + 1"
position = "before"
payload = '''
SMODS.calculate_context({cs_beforeall = true, cs_scoring_hand = scoring_hand})
text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)
'''
match_indent = true




# Context to get the score of the hand played
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "check_for_unlock({type = 'chip_score', chips = math.floor(hand_chips*mult)})"
position = "after"
payload = '''
SMODS.calculate_context({cs_check_score = true})
'''
match_indent = true
